# Project: QuizRelease
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = QuizRelease_private.res
OBJ      = QuizRelease.o Menu.o CreativeCommons.o $(RES)
LINKOBJ  = QuizRelease.o Menu.o CreativeCommons.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lgdi32 -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = QuizRelease.exe
CXXFLAGS = $(CXXINCS) -g3 -finput-charset=utf-8
CFLAGS   = $(INCS) -g3 -finput-charset=utf-8
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

QuizRelease.o: QuizRelease.cpp
	$(CPP) -c QuizRelease.cpp -o QuizRelease.o $(CXXFLAGS)

Menu.o: Menu.cpp
	$(CPP) -c Menu.cpp -o Menu.o $(CXXFLAGS)

CreativeCommons.o: CreativeCommons.cpp
	$(CPP) -c CreativeCommons.cpp -o CreativeCommons.o $(CXXFLAGS)

QuizRelease_private.res: QuizRelease_private.rc CreativeCommons.rc
	$(WINDRES) -i QuizRelease_private.rc --input-format=rc -o QuizRelease_private.res -O coff 

